import 'dotenv/config';
import { randomBytes } from 'crypto';
import { AppDataSource } from './data-source';
import { Product } from './src/modules/products/products.entity';

const DEFAULT_COUNT = 150;

function parseCount(): number {
  // pnpm/ts-node додають у argv прапорці та "--", тому шукаємо останній числовий токен
  const numeric = process.argv
    .slice(2)
    .filter((a) => /^\d+$/.test(a))
    .map((a) => parseInt(a, 10));
  if (numeric.length === 0) return DEFAULT_COUNT;
  const n = numeric[numeric.length - 1];
  if (!Number.isFinite(n) || n < 1) {
    console.error('Usage: pnpm run db:bulk-products [count]');
    process.exit(1);
  }
  return Math.min(n, 50_000);
}

async function main() {
  const count = parseCount();
  console.log(`Bulk-seeding up to ${count} products...`);
  await AppDataSource.initialize();
  const productRepo = AppDataSource.getRepository(Product);
  const batch: Partial<Product>[] = [];
  const runId = `${Date.now().toString(36)}-${randomBytes(4).toString('hex')}`;

  for (let i = 0; i < count; i++) {
    const price = 10 + Math.floor(Math.random() * 9_990) + Math.random();
    const stock = 20_000 + Math.floor(Math.random() * 10_000);
    batch.push({
      name: `Stress item ${runId}-${i + 1}`,
      sku: `STRESS-${runId}-${i + 1}`,
      description: `Autogenerated for log/load testing (${runId})`,
      price: Math.round(price * 100) / 100,
      stock,
      isActive: true,
    });
  }

  // Insert in chunks to avoid huge single statements
  const CHUNK = 200;
  let inserted = 0;
  for (let c = 0; c < batch.length; c += CHUNK) {
    const slice = batch.slice(c, c + CHUNK);
    await productRepo.insert(slice);
    inserted += slice.length;
    process.stdout.write(`\rInserted ${inserted}/${batch.length}`);
  }
  console.log('\nDone.');
  await AppDataSource.destroy();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
